version: "3.7"

services:
  app:
    container_name: card_service
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=12
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  db:
    image: postgres:10.6-alpine
    container_name: db-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  
volumes:
  db-data:
